"use client"
import './globals.css'
import { Provider } from "react-redux";
import { store } from './redux/store';



// export const metadata = {
//   title: 'Dialog',
//   description: 'Generated by create next app',
//   icons: {
//     icon: [
//       {
//         // media: '(prefers-color-scheme: dark)',
//         url: '/images/logo.png',
//         href: '/images/logo.png',
//       },
//     ],
//   },
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="preconnect" href="https://fonts.googleapis.com"/>
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
      <link href="https://fonts.googleapis.com/css2?family=Audiowide&family=Comfortaa:wght@400;500;600;700&family=Red+Hat+Display:wght@400;500;600;700&display=swap" rel="stylesheet"/>      

      <Provider store={store}>
        <body className='w-screen h-screen flex justify-center items-center'>
          {children}
        </body>
      </Provider>
    </html>
  )
}
